version: "3.9"
services:
  web:
    # image: neeejm/ssii-devoir:latest
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - env.docker.properties
  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    env_file:
      - env.docker.properties